[WIP] views.md
translation-gang/ru.docs.laravel pull request #1
Opened 2017-02-12 19:41 UTC by agoalofalife

Разделы которые буду переводить
- [ ] Creating Views
- [ ] Passing Data To Views
- [ ] Sharing Data With All Views
- [ ] View Composers
`По срокам максимально до 19.02.17`

2017-02-14 08:31 UTC, agoalofalife commented
Старался переводить по тексту ,если фразы где то не звучат "по - русски " могу изменить

2017-02-14 13:04 UTC, ilyahoilik commented
Для внимания ревьюера. В меню `Views` переведено как `Представления`, однако тут - как `Шаблоны`.  Шаблоны звучит мягче, однако Представления - точнее. Как говорится, думайте сами, решайте сами :)

2017-02-14 13:18 UTC, agoalofalife commented
В обще в тексте старался разбавлять `Шаблоны` и `Представления` , так как парой `views` очень часто один за другим идут в тексте, и если переводить все как есть , режет слух для русского человека.  Надо понять просто  переводить чтобы не резало слух, или стараться точь в точь переводить)

2017-02-14 14:17 UTC, jhaoda requested changes
- [ ] В переводе много кальки, неплохо бы локализовать, а так же прогнать через проверку орфогафии. И рекомендую типографскую раскладку Ильи Бирмана для улучшения типографики.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Внутри шаблонов содержится HTML разметка, предназначенная для удобства работы в приложении. С ее помощью можно отделять бизнес - логику от представления. Views расположены в директории `resources/vie
«бизнес - логику» → «бизнес—логику»
«Итак, давайте рассмотрим ...» — «Итак» лишнее.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Как вы видите, первый параметр в helper `view` соответствует названию файла в папке `resources/views`. Вторым аргументом передается массив с данными, который доступен в представлении. В этом случае,
«В этом случае,» — запятая не нужна.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Конечно, шаблоны могут быть вложены в субдиректории, в директории `resources/views`. Для ссылки на вложенные шаблоны используем нотацию "точка". Для примера, если шаблон хранится внутри: `resources/v
«субдиректории» — калька, используйте хотя бы «поддиректории».

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Если нужно определить существует ли ваше представление, вы можете использовать фасад `View`. Метод `exists`  вернут `true`, если существующий шаблон:
«вернут» → «вернёт»

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Когда мы передаем информацию таким способом, `$data` должен быть массивом с парой ключ/значение. Внутри шаблона, можно получить доступ к каждому значению, используя соответствующий ключ, такой как: `
«, для добавления отдельных кусков с данными» — запятатя не нужна, слово «кусков» не к месту.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Время от времени, придется поделиться частью своих данных со всеми представлениями, которые находятся в вашем приложении. Можно реализовать это, используя метод фасада `share`. Как правило, нужно выз
«Время от времени,» — запятая не нужна.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Для примера, давайте зарегистрируем композер внутри [сервис провайдера](/docs/{{version}}/providers). Мы будем использовать фасад `View` для доступа к реализации основного контракта `Illuminate\Contr
«поэтому можно самостоятельно организовать директорию» — «поэтому вы можете сами создать папку», учитывая что в следующем приложении используется именно слово «папка».

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +> {note}    Помните, если вы создали сервис провайдер, внутри которого зарегистрирован композер, необходимо добавить его в массив `providers` внутри конфигурационного файла в папке `config/app.php`.
«внутри конфигурационного файла в папке `config/app.php`» — это указание на файл.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Теперь когда мы зарегистрировали композер, метод `ProfileComposer@compose` будет вызываться каждый раз, когда `profile` будет рендериться. Итак, давайте определим класс композера:
«Теперь когда» — «Теперь, когда». «Итак» снова лишнее.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +Перед тем как ваш шаблон начнет рендериться, композер вызовет метод `compose` с экземпляром `Illuminate\View\View`. Вы можете использовать метод  `with`, для привязки данных к представлению.
«`with`, для» — запятая не нужна.

2017-02-14 14:17 UTC, jhaoda commented on views.md
> +> {tip} Все композеры разрешаются через [сервис контейнер](/docs/{{version}}/container), поэтому можно применить любую инъекцию зависимостей внутри конструктора.
Полагаю, для новичков будет не очень понятно, что в данном случае означает «разрешаются».

2017-02-14 14:19 UTC, jhaoda commented
Так же замечу, что в данном разделе я строго за использование «представление», а не «шаблон».

2017-02-14 14:38 UTC, agoalofalife commented
Хорошо учту все и поправлю

2017-02-14 14:48 UTC, agoalofalife commented on views.md
> +Внутри шаблонов содержится HTML разметка, предназначенная для удобства работы в приложении. С ее помощью можно отделять бизнес - логику от представления. Views расположены в директории `resources/vie
@jhaoda а что имеется в виду локализовать?Через орфографию прогнал

2017-02-14 14:54 UTC, jhaoda commented on views.md
> +Внутри шаблонов содержится HTML разметка, предназначенная для удобства работы в приложении. С ее помощью можно отделять бизнес - логику от представления. Views расположены в директории `resources/vie
@agoalofalife это то, о чем вы писали выше — «если фразы где то не звучат "по - русски " могу изменить». Т.е. сейчас перевод слишком дословный, это же перехваченная шифровка, которую переводят чуть ли не посимвольно, что бы не потерять важное.
Локализация это очеловечивание, замена дословного перевода на принятые в русской языке речевые обороты.

2017-02-14 15:26 UTC, gbezyuk commented
@jhaoda если есть чёткое понимание, как именно поправить тот или иной момент — оптимальнее сразу самому и править.

2017-02-14 15:32 UTC, jhaoda commented
@gbezyuk и понимание не всегда, и возможности форкнуть и поправить тоже. Я выберу время и пройдусь с правками по законченым разделам.

2017-02-14 15:34 UTC, gbezyuk commented
@jhaoda форкать не надо, в рамках PR есть доступ на прямые коммиты и правку через веб-интерфейс.

2017-02-14 15:37 UTC, gbezyuk commented
<img width="1110" alt="screen shot 2017-02-14 at 18 36 08" src="https://cloud.githubusercontent.com/assets/1452165/22935770/96baeef0-f2e4-11e6-957c-d9a2787b009b.png">
<img width="1040" alt="screen shot 2017-02-14 at 18 35 39" src="https://cloud.githubusercontent.com/assets/1452165/22935768/96b98d1c-f2e4-11e6-9946-29863e746a09.png">
<img width="732" alt="screen shot 2017-02-14 at 18 35 08" src="https://cloud.githubusercontent.com/assets/1452165/22935767/96b86ce8-f2e4-11e6-8bdc-58aa6ec78e4f.png">

2017-02-14 15:37 UTC, jhaoda commented
@gbezyuk да увидел уже. Куда смотрел-то...

2017-02-14 15:42 UTC, ilyahoilik commented
@gbezyuk это у ограниченного круга лиц такой доступ? Ибо у меня этого нет. Хотел добавить пропущенное слово в PR другого человека, пришлось самому создавать новый PR в его форк.

![2017-02-14_18-40-41](https://cloud.githubusercontent.com/assets/7265704/22935954/1db3f334-f2e5-11e6-9f17-38df46db082b.png)

![2017-02-14_18-41-11](https://cloud.githubusercontent.com/assets/7265704/22935978/2d4fce1c-f2e5-11e6-906c-8aafaa82e79c.png)

2017-02-14 15:45 UTC, gbezyuk commented
@ilyahoilik это у членов TG

2017-02-14 15:48 UTC, ilyahoilik commented
Понял :)

2017-02-14 22:06 UTC, gbezyuk commented
ping @jhaoda @ilyahoilik — давайте пофиксим и смерджим

2017-02-14 22:15 UTC, ilyahoilik commented
Окей, сейчас закончу contributions и перейду к этому

2017-02-14 22:47 UTC, ilyahoilik commented
@gbezyuk я разве что через отдельный PR могу. То есть, насколько я понимаю, придётся сначала смержить этот. И только потом мержить мой.

2017-02-14 23:41 UTC, gbezyuk commented
@ilyahoilik ты можешь просто к этому бранчу коммитов добавить.

2017-02-14 23:47 UTC, ilyahoilik commented
@gbezyuk попробовал изменить views.md в его бранче. Вот такая вот надпись при изменении файла:

> You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork ilyahoilik/ru.docs.laravel, so you can send a pull request.

Делать?

2017-02-14 23:52 UTC, gbezyuk commented
@ilyahoilik ща добавим тебя в TG )

2017-02-14 23:53 UTC, gbezyuk commented
@ilyahoilik лови инвайт и пробуй ещё раз ;)

2017-02-14 23:55 UTC, ilyahoilik commented
@gbezyuk, изменение стало доступно, спасибо :)

2017-02-15 00:42 UTC, ilyahoilik commented
@gbezyuk @jhaoda поправил проблемы из списка выше, заменил "шаблоны" на "представления" и исправил другие ошибки.

2017-02-15 04:52 UTC, jhaoda approved these changes

2017-02-15 05:33 UTC, agoalofalife commented
Я хотел сегодня внести правки @jhaoda

2017-02-16 05:41 UTC, merged